name: Build All

on:
  workflow_dispatch:
    inputs:
      go_version:
        type: string
        required: false
        default: "1"
        description: "version of go (default = 1.0)"
      hugo_version:
        type: string
        required: false
        default: "v0.110.0"
        description: "version of go (default = v0.110.0)"

  push:
    branches:
      - master
    paths-ignore:
      - "LICENSE"
      - "**/README.md"
      - "docs/*"

jobs:
  build-hugo-vscode:
    name: Build hugo-vscode
    uses: ulfsoft-harbour/go/.github/workflows/build-and-push.yaml@master
    with:
      target: hugo-vscode
      go_version: ${{ github.event.inputs.go_version }}
      hugo_version: ${{ github.event.inputs.hugo_version }}
